services:
  log_analyzer:
    container_name: log_analyzer_cont
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: ./.env
    shm_size: 2gb
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - ${API_SERVER_PORT}:8080
    volumes:
      - type: bind
        source: ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/log_analyzer
        target: /home/user1/log_analyzer/volumes/log_analyzer
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mariadb
    image: mariadb:11.5
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/store:/var/lib/mysql
      - ./app/static/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mysql-admin:
    container_name: mariadb-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PMA_GUI_PORT}:80
    mem_limit: 512m
    depends_on:
      - mysql
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

networks:
  default:
    name: log_analyzer_net